// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CarouselController from "./carousel_controller"
application.register("carousel", CarouselController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import SidebarController from "./sidebar_controller"
application.register("sidebar", SidebarController)

import ThemeToggleController from "./theme_toggle_controller"
application.register("theme-toggle", ThemeToggleController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import ActiveLinkController from "./active_link_controller"
application.register("active-link", ActiveLinkController)

import LiveSearchController from "./live_search_controller"
application.register("live-search", LiveSearchController)

import SlotExceptionController from "./slot_exception_controller"
application.register("slot-exception", SlotExceptionController)
